import { ExtensionItem } from "../types";

export const EXTENSIONS_CATALOG: ExtensionItem[] = [
  {
    id: "esbenp.prettier-vscode",
    name: "prettier-vscode",
    displayName: "Prettier - Code formatter",
    publisher: "esbenp",
    version: "10.4.0",
    downloads: "44.2M",
    rating: 4.8,
    ratingCount: 3820,
    description: "An opinionated code formatter. It enforces a consistent style by parsing your code and re-printing it with its own rules that take the maximum line length into account, wrapping code when necessary.",
    category: "Formatters",
    iconBg: "bg-[#1a202c]",
    iconText: "✨",
    installed: true,
    enabled: true,
    readme: `# Prettier - Code formatter\n\nVS Code package to format your JavaScript / TypeScript / CSS / HTML using Prettier.\n\n## Installation\nClick install and set as default formatter in settings:\n\`\`\`json\n{\n  "editor.defaultFormatter": "esbenp.prettier-vscode",\n  "editor.formatOnSave": true\n}\n\`\`\`\n\n## Supported Languages\n- JavaScript & JSX\n- TypeScript & TSX\n- CSS, Less, SCSS\n- JSON & YAML\n- Markdown`,
    settings: {
      "prettier.singleQuote": { type: "boolean", default: true, description: "Use single quotes instead of double quotes." },
      "prettier.tabWidth": { type: "number", default: 2, description: "Number of spaces per indentation-level." },
      "prettier.semi": { type: "boolean", default: true, description: "Print semicolons at the ends of statements." },
    },
  },
  {
    id: "dbaeumer.vscode-eslint",
    name: "vscode-eslint",
    displayName: "ESLint",
    publisher: "Microsoft",
    version: "3.0.10",
    downloads: "36.8M",
    rating: 4.5,
    ratingCount: 2940,
    description: "Integrates ESLint into VS Code. If you haven't installed ESLint either globally or locally then run \`npm install eslint\` in the workspace folder.",
    category: "Linters",
    iconBg: "bg-[#4b32c3]/20",
    iconText: "🛡️",
    installed: true,
    enabled: true,
    readme: `# ESLint for VS Code\n\nIntegrates ESLint into VS Code and Monaco editor.\n\n## Features\n- Real-time syntax checking\n- Auto-fix on save\n- Configurable rule severity (Warning, Error, Info)`,
  },
  {
    id: "bradlc.vscode-tailwindcss",
    name: "vscode-tailwindcss",
    displayName: "Tailwind CSS IntelliSense",
    publisher: "Tailwind Labs",
    version: "0.14.3",
    downloads: "19.5M",
    rating: 4.9,
    ratingCount: 1650,
    description: "Intelligent Tailwind CSS tooling for VS Code that enhances the user experience with advanced features such as autocomplete, syntax highlighting, and linting.",
    category: "Languages",
    iconBg: "bg-[#06b6d4]/20",
    iconText: "🎨",
    installed: true,
    enabled: true,
    readme: `# Tailwind CSS IntelliSense\n\nAdvanced autocomplete, class sorting, color previews, and hover documentation for Tailwind CSS.`,
  },
  {
    id: "teminali.video-copilot",
    name: "teminali-cut-mcp",
    displayName: "Teminali Cut Video Copilot MCP",
    publisher: "Teminali Labs",
    version: "1.12.5",
    downloads: "120.4K",
    rating: 5.0,
    ratingCount: 520,
    description: "Autonomous Video Timeline Editing MCP Server. Provides real-time beat synchronization, kinetic captions, auto-silence removal, and color grading over JSON-RPC port 3888.",
    category: "AI & MCP",
    iconBg: "bg-[#8b5cf6]/20",
    iconText: "🎬",
    installed: true,
    enabled: true,
    readme: `# Teminali Cut Video Copilot MCP\n\nDirect AI video timeline editing bridge.\n\n## Tools Exposed\n- \`detect_silence_and_split\`: Removes dead pauses\n- \`sync_cuts_to_audio_beats\`: Snaps cuts to transients\n- \`add_kinetic_highlight_captions\`: Generates animated captions\n- \`apply_cinematic_grade\`: Color grading filters`,
  },
  {
    id: "ms-python.python",
    name: "python",
    displayName: "Python",
    publisher: "Microsoft",
    version: "2025.2.0",
    downloads: "132.8M",
    rating: 4.6,
    ratingCount: 8400,
    description: "Rich support for the Python language (including Python 3.12+), including features such as IntelliSense (Pylance), linting, debugging, code navigation, code formatting, and refactoring.",
    category: "Languages",
    iconBg: "bg-[#3776ab]/20",
    iconText: "🐍",
    installed: false,
    enabled: false,
    readme: `# Python Extension for VS Code\n\nIndustry-standard Python development environment for VS Code.`,
  },
  {
    id: "rust-lang.rust-analyzer",
    name: "rust-analyzer",
    displayName: "rust-analyzer",
    publisher: "The Rust Team",
    version: "0.4.2320",
    downloads: "6.2M",
    rating: 4.9,
    ratingCount: 2100,
    description: "Rust language support with full autocomplete, go-to-definition, type inference, hover tooltips, and macro expansion.",
    category: "Languages",
    iconBg: "bg-[#f97316]/20",
    iconText: "🦀",
    installed: false,
    enabled: false,
    readme: `# rust-analyzer\n\nModular compiler frontend for the Rust language in VS Code.`,
  },
  {
    id: "eamodio.gitlens",
    name: "gitlens",
    displayName: "GitLens — Git supercharged",
    publisher: "GitKraken",
    version: "16.1.2",
    downloads: "34.5M",
    rating: 4.7,
    ratingCount: 4120,
    description: "Supercharge Git within Teminali Studio — Visualize code authorship at a glance via Git blame annotations and CodeLens.",
    category: "Tools",
    iconBg: "bg-[#10b981]/20",
    iconText: "🌿",
    installed: false,
    enabled: false,
    readme: `# GitLens\n\nGit supercharged inside your editor.`,
  },
  {
    id: "dracula-theme.theme-dracula",
    name: "dracula-theme",
    displayName: "Dracula Official",
    publisher: "Dracula Theme",
    version: "2.25.1",
    downloads: "8.9M",
    rating: 4.9,
    ratingCount: 1890,
    description: "Official Dracula Theme. A dark theme for 40+ apps including VS Code and Monaco.",
    category: "Themes",
    iconBg: "bg-[#282a36]",
    iconText: "🧛",
    installed: false,
    enabled: false,
    readme: `# Dracula Theme\n\nThe iconic dark theme for hackers and engineers.`,
  },
];
